# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    #active: druid-dev,prod
    active: druid-prod,prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  500MB
      # 设置总上传的文件大小
      max-request-size:  2000MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
