# 项目相关配置
ruoyi:
  # 名称
  name: qwk
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
#  profile: /home/ruoyi/uploadPath
  profile: uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

## Spring配置
spring:
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: werfg8965236u
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyzQWK123456
    # 令牌有效期（分钟）
    expireTime: 43776
    # 是否允许账户多终端同时登录（true允许 false不允许）
    soloLogin: false

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#腾讯云短信配置
tencent:
  smsAppId: 1400834660
  smsAppKey: "b1bdaf0493bf950a6d59339b1faebcd4"
  smsTemplateId: 1847993
  smsSign: "仟万客网络科技有限公司"
#腾讯云IM即时通话配置
IMConfig:
  sdkAppId: 1600006190
  secretKey: 119148643a19fe53c58af79300797e4decb71f07b4bf71509b3a8895c702919e
txyApi:
  secretId: AKIDzsb9Vp363ymPGsKbgXAlO0dC8vV1OyLV
  secretKey: 9A2unX8UggYQ8eDeAYmuxursoY4PbjgV
#腾讯云COS存储
tencentCosUtil:
  #开发者拥有的项目身份识别 ID，用于身份认证，可在 API 密钥管理 页面获取
  secretId: AKIDTo18CQdjeR1NYmaHl3xQ1Xt57zjT6Ypx
  #开发者拥有的项目身份密钥，可在 API 密钥管理 页面获取
  secretKey: 96uY2LRWRFsKrBKH3d1CD1c2IPJ2e7RZ
  #存储桶名称格式，用户在使用 API、SDK 时，需要按照此格式填写存储桶名称
  bucketName: hbqwk-1318352516
  #存储桶配置管理中访问域名的URL（格式：https://bucketName.cos.所在地域（例如：ap-nanjing）.myqcloud.com/）
  accessUrl: https://hbqwk-1318352516.cos.ap-shanghai.myqcloud.com/
#  极光推送
jpush:
  appKey: 69735a3475db5af24a45a838
  masterSecret: 51b02d25dae903d81397b5d2
  apnsProduction: false   # 是否生成环境，true表示生成环境
# 分享链接配置
share:
  # 分享链接url
  url: https://admin.wlxxl.top/
